version: '3'
services:
  dashboard:
    container_name: dashboard
    restart: always
    build: ./
    env_file: .env.local
    networks:
      - almond_almond-network

networks:
  almond_almond-network:
    external: true
